# Generated by Django 6.0.5 on 2026-05-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Joylashuv/Tavsif"
                    ),
                ),
                (
                    "cam_username",
                    models.CharField(max_length=100, verbose_name="Foydalanuvchi nomi"),
                ),
                (
                    "cam_password",
                    models.CharField(max_length=100, verbose_name="Parol"),
                ),
                ("ip", models.CharField(max_length=50, verbose_name="IP manzil")),
                ("port", models.PositiveIntegerField(default=554, verbose_name="Port")),
                ("resolution", models.CharField(default="1920x1080", max_length=20)),
                ("fps", models.PositiveIntegerField(default=25)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Kamera",
                "verbose_name_plural": "Kameralar",
                "ordering": ["id"],
            },
        ),
    ]
